### PR TITLE
Issue #645 Custom CopilotKit Content solved

### PR DESCRIPTION
**Pull request by Mayank77maruti**
Custom CopilotKit Content solved.

### CODE REVIEW

**Comment by NathanTarbert** [comment]
Hey @Mayank77maruti, the dev.to link takes me to a 404.

**Comment by Mayank77maruti** [comment]
Hi @NathanTarbert sir ,
I have added post on dev.to you check here https://dev.to/mayank_mohapatra/copilotkit-2dik
Screenshot 2024-10-04 011929
but donot know why they got my account banned for the posting the same from my previous account

**Comment by NathanTarbert** [comment]
@Mayank77maruti, please leave this Issue open but add your file.
Also, please remove the spaces in the file name and insert a hyphen between (my-custom-content.md)
Give the file a unique name; you can use something like -  name-custom-content.md

**Comment by Mayank77maruti** [comment]
Sir i have changed the file name but i didnot get "please leave this Issue open but add your file" that you mentioned.

**Comment by Mayank77maruti** [comment]
Sir should i push the changes from a new branch without tagging the issue.

**Review by NathanTarbert — APPROVED** [review]

**Comment by NathanTarbert** [comment]
Thank you @Mayank77maruti!

**Comment by Mayank77maruti** [comment]
Your most welcome sir.

**Pull request merged**
