### PR TITLE
Fixed readme.md

### PR DESCRIPTION
**Pull request by atomnoid**
Fixed some of the readme issues by rephrasing it. The changes i made will give you more quality and help users to understand the guide easily.

### CODE REVIEW

**Comment by atomnoid** [comment]
@NathanTarbert @arielweinberger hey please check my pr my first contribution for hactober fest

**Comment by NathanTarbert** [comment]
@atomnoid, please only commit the file (README.md) you are changing.

**Comment by atomnoid** [comment]
> @atomnoid, please only commit the file (README.md) you are changing.
Okay I'm creating a fresh pull request with the same changes please review it

**Comment by arielweinberger** [comment]
I do not believe that this readme change will provide value in terms of messaging. We'll leave the messaging as-is. Additionally, the text has a bunch of typos. I appreciate your interest in contributing @atomnoid, I suggest trying to contribute a demo instead.

**Pull request closed without merging**
