### PR TITLE
demo: AI powered GitHub Pull Request Tracker

### PR DESCRIPTION
**Pull request by JeevaRamanathan**
## What does this PR do?

Added demo of GitHub pull requested tracker that is using copilotkit

## Related PRs and Issues

NA

## Checklist

- [x] I have read read the [Contribution Guide](https://github.com/copilotkit/copilotkit/blob/master/CONTRIBUTING.md)
- [x] If the PR changes or adds functionality, I have updated the relevant documentation

### CODE REVIEW

**Comment by JeevaRamanathan** [comment]
@quest-bot embark

**Comment by JeevaRamanathan** [comment]
@quest-bot loot #829

**Comment by JeevaRamanathan** [comment]
Hi @mme, @NathanTarbert can you please have a look into this?

**Review by NathanTarbert — APPROVED** [review]

**Comment by NathanTarbert** [comment]
Awesome job @JeevaRamanathan!

**Pull request merged**
