### PR TITLE
⭐ 22 - Study Buddy (Hacktoberfest Demo) #634

### PR DESCRIPTION
**Pull request by kom-senapati**
## What does this PR do?

Add a demo for study buddy

## Checklist

- [X] I have read read the [Contribution Guide](https://github.com/copilotkit/copilotkit/blob/master/CONTRIBUTING.md)
- [x] If the PR changes or adds functionality, I have updated the relevant documentation

### CODE REVIEW

**Comment by NathanTarbert** [comment]
Hi @kom-senapati, great job. 
One thing I noticed is when I add a study plan with a title and description it goes into a loop and fills the whole screen with the same plan. 
image

Can you look into this?

**Comment by kom-senapati** [comment]
@NathanTarbert It's actually a problem with the model used. If we used GPT-3.5 or something similar, the results would be better. I am using a Groq model for this, so it gives results like that.

I think the input should be like "I want a plan for learning algebra".

**Review by NathanTarbert — APPROVED** [review]

**Comment by NathanTarbert** [comment]
Nice one @kom-senapati!!!😃

**Comment by kom-senapati** [comment]
@quest-bot loot #634

**Pull request merged**
