### PR TITLE
Added community demo: Cal Buddy

### PR DESCRIPTION
**Pull request by ChiragAgg5k**
Added my project, Cal Buddy, in community demos.

thumbnail

### CODE REVIEW

**Comment by ChiragAgg5k** [comment]
For the issue #606

**Comment by ChiragAgg5k** [comment]
@NathanTarbert please do review the pr once u can. thanks!

**Review by NathanTarbert — APPROVED** [review]

**Comment by NathanTarbert** [comment]
Nicely done @ChiragAgg5k!

**Comment by ChiragAgg5k** [comment]
@quest-bot loot #606

**Pull request merged**
