### PR TITLE
Added error handling for Open AI requests.

### PR DESCRIPTION
**Pull request by thesloppyguy**
If no error:
ksnip_20231217-194020
else:
ksnip_20231217-194328

/claim #64

### CODE REVIEW

**Comment by thesloppyguy** [comment]
@ataibarkai This fixes #64. Do you have any changes in mind? if not please review and merge. 🙏

**Comment by ataibarkai** [comment]
thank you @thesloppyguy.
 Looks good, only thing is- do you mind resolving the merge conflicts?

**Comment by thesloppyguy** [comment]
@ataibarkai Merged main into the branch. should be up to date now.

**Comment by ataibarkai** [comment]
Thank you @thesloppyguy !

**Pull request merged**
