### PR TITLE
Hacktoberfest contribution for Travel Budget Planner #636       and Customer Support bot       #786   

### PR DESCRIPTION
**Pull request by Zedoman**
## What does this PR do?
1. !st pr of Travel budget Planner: TravelTally is a travel budget planner that allows users to efficiently manage their finances by tracking expenses related to their trips, including airfare, lodging, and activities. Users can monitor their budgets, view how much money they have spent compared to their allocated budget, and receive assistance from a built-in Copilot assistant. The application features a clean, responsive UI built with TailwindCSS, while leveraging React and Redux for robust state management, along with CopilotKit and Shadcn-UI for enhanced functionality and styling.

2. 2nd pr of customer support Bot: [SwiftSupport](https://customer-bot-three.vercel.app/) - A Real-Time AI-Powered Chatbot for Customer Support
This Customer Support Chatbot is designed to assist Customers in providing AI-driven customer service. It leverages the Google Generative AI model via CopilotKit to handle customer queries in real-time, offering automated and intelligent responses.

## Checklist

- [X ] I have read read the [Contribution Guide](https://github.com/copilotkit/copilotkit/blob/master/CONTRIBUTING.md)
- [ X] If the PR changes or adds functionality, I have updated the relevant documentation

### CODE REVIEW

**Comment by Zedoman** [comment]
@NathanTarbert sir i have updated the pr against #636 if you please check it and approve it.

**Comment by Zedoman** [comment]
@quest-bot loot #636

**Comment by Zedoman** [comment]
@quest-bot loot #786

**Comment by Zedoman** [comment]
@NathanTarbert sir i have updated the prs against #636 and #786  if you please check it and approve it.

**Review by NathanTarbert — APPROVED** [review]

**Comment by NathanTarbert** [comment]
Excellent job @Zedoman!

**Comment by Zedoman** [comment]
Thank you sir @NathanTarbert

**Pull request merged**
