### PR TITLE
17 - Interactive Flashcards (Hacktoberfest Demo) #629

### LINKED ISSUE #629: ⭐ 17 - Interactive Flashcards (Hacktoberfest Demo)
### 🤩 Thank you for participating in the CopilotKit Hacktoberfest event. 

Follow [This Link to Get Started!](https://github.com/CopilotKit/CopilotKit/tree/main/community/content)🎉

#### NOTE: CopilotKit will allow multi-assign issues

  Please show your support and give a ⭐ to the CopilotKit repository.

### Description of app functionality:
Create a learning app that allows users to create flashcards for studying and quizzes them interactively

#### Using CopilotKit
- **Required**: Your project must utilize CopilotKit as a core component.
- **Installation**: Include CopilotKit by following the installation guide at [CopilotKit Quickstart](https://docs.copilotkit.ai/quickstart).
- **Documentation**: Familiarize yourself with CopilotKit's features through the [Official Documentation](https://docs.copilotkit.ai).

#### Styling with Shadcn-UI
- **Required**: All UI components in your project should be styled using Shadcn-UI.
- **Installation**: Install Shadcn-UI [documentation](https://ui.shadcn.com/docs/installation)

Swag_2

### PR DESCRIPTION
**Pull request by Niharika0104**
**Description:**
QuizFlip is an app that generates flashcards on any topic you ask for, helping users learn and review efficiently. It integrates with CopilotKit to generate flashcards and quizzes quickly and accurately.

image

image

### CODE REVIEW

**Comment by NathanTarbert** [comment]
Hi @Niharika0104, can you please unlink Issue #629? 

We want to leave it open until Hacktoberfest ends.

**Review by NathanTarbert — CHANGES_REQUESTED** [review]
@Niharika0104, please remove all files except the markdown file `/community/demos/etc.md`

**Comment by Niharika0104** [comment]
@NathanTarbert Can you check it now?

**Review by NathanTarbert — APPROVED** [review]

**Comment by NathanTarbert** [comment]
Nice @Niharika0104!

**Pull request merged**
