### PR TITLE
feat/#608 daily quote app

### PR DESCRIPTION
**Pull request by nitesh2920**
## What does this PR do?

This PR introduces a Daily Quote App that offers motivational, educational, and a variety of other quotes. Users can share their own quotes and even use Copilot to generate amazing new ones.

## Related PRs and Issues
- [LiveLink](https://jarvis-quote.vercel.app/)
- [Github Repo](https://github.com/nitesh2920/JarvisQuote)

## Checklist

- [x] I have read read the [Contribution Guide](https://github.com/copilotkit/copilotkit/blob/master/CONTRIBUTING.md)
- [x] If the PR changes or adds functionality, I have updated the relevant documentation

### CODE REVIEW

**Review by NathanTarbert — APPROVED** [review]

**Comment by NathanTarbert** [comment]
Great job @nitesh2920!

**Comment by nitesh2920** [comment]
@quest-bot loot #846

**Comment by nitesh2920** [comment]
> Great job @nitesh2920!

Thank You

**Comment by nitesh2920** [comment]
@NathanTarbert I’d like to include a bonus section featuring links to my Twitter and Dev blog. Since they have been merged, do I need to raise a new PR for this addition?

**Comment by NathanTarbert** [comment]
Yes, quickly submit a PR, and I'll merge it

**Comment by nitesh2920** [comment]
> Yes, quickly submit a PR, and I'll merge it

okay, raised a PR #862 please check it.

**Comment by nitesh2920** [comment]
@quest-bot loot

**Comment by nitesh2920** [comment]
@quest-bot loot #608

**Comment by nitesh2920** [comment]
@nitesh2920 quest close mean will I not receive a swag?

**Pull request merged**
