### PR TITLE
email-organizer added

### PR DESCRIPTION
**Pull request by Rishikesh63**
## What does this PR do?

This PR introduces the Email Organizer application, an AI-powered tool that categorizes email content based on urgency, sender, and content type. The changes include:

- Backend Integration: Utilizes OpenAI's model to analyze and categorize emails based on predefined criteria like urgency and sender details.
- Frontend Interface: Developed using Next.js and styled with Tailwind CSS, providing a responsive and user-friendly design.
- Real-time Updates: Implements dynamic state management using React hooks (useState, useEffect), ensuring a seamless user experience.

- Error Handling & API Optimization: Introduces robust error handling and enhances API response times for smooth interactions.
- Adding a new demo application in the community/demos directory

## Related PRs and Issues

- (Direct link to related PR or issue)
 https://email-organizer-7vs97j141-rishikesh-maddhesiyas-projects.vercel.app/

## Checklist

- [X] I have read read the [Contribution Guide](https://github.com/copilotkit/copilotkit/blob/master/CONTRIBUTING.md)
- [X] If the PR changes or adds functionality, I have updated the relevant documentation

### CODE REVIEW

**Comment by NathanTarbert** [comment]
@Rishikesh63, please remove the package.json and lock files. 
Only add the markdown file.

**Comment by Rishikesh63** [comment]
> @Rishikesh63, please remove the package.json and lock files. Only add the markdown file.

I have added markdown file in demo directory

**Comment by Rishikesh63** [comment]
@NathanTarbert  I have added  the markdown file in another commit ,is i need to remove this commit in this commit i have added  whole email-organizer project

**Review by NathanTarbert — CHANGES_REQUESTED** [review]
Please remove all files except the markdown file

**Pull request closed without merging**
