### PR TITLE
receipe generator added

### PR DESCRIPTION
**Pull request by Mayank77maruti**
## What does this PR do?

receipe

## Related PRs and Issues
[Link](https://receipe-generator-1zyq.vercel.app/)
[dev to](https://dev.to/mayank_mohapatra/recipe-generator-powered-by-copilotkit-chatbot-1mlg)

## Checklist

- [x] I have read read the [Contribution Guide](https://github.com/copilotkit/copilotkit/blob/master/CONTRIBUTING.md)
- [x] If the PR changes or adds functionality, I have updated the relevant documentation

### CODE REVIEW

**Comment by Mayank77maruti** [comment]
Hey @NathanTarbert , this pr is ready to be reviewed.
Please do review it.
Thank you

**Review by NathanTarbert — APPROVED** [review]

**Comment by NathanTarbert** [comment]
Awesome @Mayank77maruti!

**Comment by Mayank77maruti** [comment]
@quest-bot loot #603

**Comment by NathanTarbert** [comment]
@Mayank77maruti, I'm following up regarding the Hacktoberfest swag. 
Please send me an email @ nathan@copilotkit.ai

- First and Last Name
- Project Name
- Twitter Handle
- T-shirt size
- Address

Note: I must receive a reply within 14 days or this message will be void

**Pull request merged**
