### PR TITLE
Added demo and Content : CopilotMate

### PR DESCRIPTION
**Pull request by AkashJana18**
Hacktoberfest submission

### CODE REVIEW

**Comment by NathanTarbert** [comment]
Hi @AkashJana18, excellent job! 

Can you please unlink the issues

We want to leave them open until Hacktoberfest ends.

**Comment by AkashJana18** [comment]
Sure @NathanTarbert :)

**Comment by NathanTarbert** [comment]
@AkashJana18, please remove all files except markdown.

**Comment by AkashJana18** [comment]
@NathanTarbert i don't see any other files attached to PR except the copilotmate.md

**Comment by AkashJana18** [comment]
@quest-bot loot #645

**Comment by AkashJana18** [comment]
@quest-bot loot #634

**Comment by AkashJana18** [comment]
@quest-bot loot #644

**Comment by AkashJana18** [comment]
@quest-bot loot #626

**Review by NathanTarbert — APPROVED** [review]

**Pull request merged**
