### PR TITLE
📚 Documentation Improvements: Typos and Readability Enhancements ✏️

### PR DESCRIPTION
**Pull request by LitZeus**
### Overview
This pull request addresses various documentation issues, focusing on fixing typos, improving readability, and ensuring consistency throughout the documentation. ✨📚 This PR fixes issue #643 and also addresses redundancies identified in issue #677.

### Changes Made
- **Fixed Links**: Corrected the **generative-ui** link for proper navigation. 🔗
- **Capitalization Consisitency**: Changed `copilots` to `Copilots` in relevant sections. 🛠️
- **Added Title**: Added **"Bring Your Own LLM"** title for clarity. 📄
- **Adjusted Font Weight**: Corrected font-weight from **"a"** to **"a"**. ✏️
- **Terminology Normalization**: 
  - Changed **Self Hosting** to **Self-Hosting**.
  - Updated **Router-mode** to **Router mode**.
  - Adjusted **Agent Lock** to **Agent-Lock**.

### Impact
These changes enhance the readability and consistency of the documentation, making it easier for users to navigate and understand the material. 📈

### Related Issues
This pull request addresses:
- Issue #643: **Documentation Cleanup: Fix Typos and Improve Readability**. 📝
- Issue #677: **Fixed redundancies identified in the documentation**.

### CODE REVIEW

**Comment by LitZeus** [comment]
### hey @arielweinberger @mme @ataibarkai Can you check my PR which can be resolving #643

**Comment by LitZeus** [comment]
#### The merge conflicts are arising due to the recent repo updating but I have enhanced the documentation as per the issue #643 and the redundancies from the #677 

###Please have a check on it @ataibarkai @mme @arielweinberger

**Comment by LitZeus** [comment]
### Hello sir! any updates?? @arielweinberger @mme @ataibarkai

**Comment by arielweinberger** [comment]
There are a bunch of conflicts @LitZeus  - we moved to a new docsite just a few days ago. Please resolve the conflicts and we'll review.

**Comment by LitZeus** [comment]
looking into the new docs, will update you when the work is done

**Comment by LitZeus** [comment]
> There are a bunch of conflicts @LitZeus - we moved to a new docsite just a few days ago. Please resolve the conflicts and we'll review.

@arielweinberger 
I reviewed the new docsite and found some issues.
I am not raising another issue as there are 2-3 documentation issues.
I am updating you in the new PR along with the changes in the documentation if that is okay to do!

**Comment by NathanTarbert** [comment]
@LitZeus, are you still working on the conflicts?

**Pull request closed without merging**
